schema = 3

[mod]
  [mod."github.com/GRbit/go-pcre"]
    version = "v1.0.1"
    hash = "sha256-oyuGwiWlmrFqD/05kp415LgA2jeBTCg4YWWkcPvauFk="
  [mod."github.com/fsnotify/fsnotify"]
    version = "v1.7.0"
    hash = "sha256-MdT2rQyQHspPJcx6n9ozkLbsktIOJutOqDuKpNAtoZY="
  [mod."github.com/gen2brain/beeep"]
    version = "v0.0.0-20240112042604-c7bb2cd88fea"
    hash = "sha256-8IV3zDjrymvL+KPgVDeUGP1XIAMaN23JRJwBjjBBfnA="
  [mod."github.com/getlantern/appdir"]
    version = "v0.0.0-20200615192800-a0ef1968f4da"
    hash = "sha256-DvZl9prlkYRpUEgn5imAXE/hYahxnTT3v7dQnX5nVA0="
  [mod."github.com/getlantern/context"]
    version = "v0.0.0-20220418194847-3d5e7a086201"
    hash = "sha256-9LOcdSOUcObG7q8PEfmNImNPUXfXxasKx/VhMPZBjvo="
  [mod."github.com/getlantern/errors"]
    version = "v1.0.4"
    hash = "sha256-ojS8oIjcZiTZZUQx9hqlyngmiIn56CEOL2h7lAkgkQo="
  [mod."github.com/getlantern/golog"]
    version = "v0.0.0-20230503153817-8e72de7e0a65"
    hash = "sha256-HOomx7GUc8jZwKTbuAMVKsguajUJQLf16jwOb6uITGI="
  [mod."github.com/getlantern/hex"]
    version = "v0.0.0-20220104173244-ad7e4b9194dc"
    hash = "sha256-oTjtFZA4X2HObe1lfjhX/azl/3xKmZ2+VZB32YHfICY="
  [mod."github.com/getlantern/hidden"]
    version = "v0.0.0-20220104173330-f221c5a24770"
    hash = "sha256-y9XZkMTMJt6gjymMoP1zdbGJ2bul99Ortcseb3RdVsE="
  [mod."github.com/getlantern/ops"]
    version = "v0.0.0-20231025133620-f368ab734534"
    hash = "sha256-43wSXgganrj1zqIly35Ejl+1oPvmtqSELGL/ZIvhu1U="
  [mod."github.com/getlantern/systray"]
    version = "v1.2.2"
    hash = "sha256-GEflgBfashORmopz8kxD7R3GRMKyF7bGE2DXr0w5nX0="
  [mod."github.com/getlantern/uuid"]
    version = "v1.2.0"
    hash = "sha256-6Zveuz4miQFL6I6V4+x3iKAfZEGeg46QzCYuTk4zCMo="
  [mod."github.com/go-logr/logr"]
    version = "v1.4.1"
    hash = "sha256-WM4badoqxXlBmqCRrnmtNce63dLlr/FJav3BJSYHvaY="
  [mod."github.com/go-logr/stdr"]
    version = "v1.2.2"
    hash = "sha256-rRweAP7XIb4egtT1f2gkz4sYOu7LDHmcJ5iNsJUd0sE="
  [mod."github.com/go-ole/go-ole"]
    version = "v1.3.0"
    hash = "sha256-tF8t3VcV71jQ4jbPL91BwR59AKDpUAFV1waIKzkXJu8="
  [mod."github.com/go-stack/stack"]
    version = "v1.8.1"
    hash = "sha256-ixcJ2RrK1ZH3YWGQZF9QFBo02NOuLeSp9wJ7gniipgY="
  [mod."github.com/go-toast/toast"]
    version = "v0.0.0-20190211030409-01e6764cf0a4"
    hash = "sha256-A2CcALnNGu+5xk3qWaIyKBUzGuJXcw1iIUOQZnCzInA="
  [mod."github.com/godbus/dbus"]
    version = "v4.1.0+incompatible"
    hash = "sha256-yb4MQBuRo4Uk38f5WhPr8QCy5lfMjFiJXfXp9kt4e7I="
  [mod."github.com/godbus/dbus/v5"]
    version = "v5.1.0"
    hash = "sha256-xOCMJpQK3KTmHTPn/CdqI4j0eENCtMmJDgAIoYqYOEY="
  [mod."github.com/gopherjs/gopherjs"]
    version = "v1.17.2"
    hash = "sha256-uNUK9RJXHaa8pIYmUp3xd3lWwwpEhJCXdnz+QpQT6js="
  [mod."github.com/gopherjs/gopherwasm"]
    version = "v1.1.0"
    hash = "sha256-AoqDjAZe8qzn2vQ83CRQpoKfbtXmJ1Bx5GX1h+qdqDM="
  [mod."github.com/hashicorp/hcl"]
    version = "v1.0.0"
    hash = "sha256-xsRCmYyBfglMxeWUvTZqkaRLSW+V2FvNodEDjTGg1WA="
  [mod."github.com/jacobsa/go-serial"]
    version = "v0.0.0-20180131005756-15cf729a72d4"
    hash = "sha256-jU7RnOBsexiPqG4BXjolYHYbURW2Ky09IXtYATbyB5c="
  [mod."github.com/jfreymuth/pulse"]
    version = "v0.1.1"
    hash = "sha256-fcPllz50gRzebPGK0NqK3MuXLZesvA6nb1qYe7TdfPo="
  [mod."github.com/lxn/walk"]
    version = "v0.0.0-20210112085537-c389da54e794"
    hash = "sha256-Znu01PINDKAGmW0LthC5Uxfw2WvbnGQw9U07f4QItu8="
  [mod."github.com/lxn/win"]
    version = "v0.0.0-20210218163916-a377121e959e"
    hash = "sha256-aEbdhcd+xYIATwUdYeuN4gZ/wymgSM5JlFZ7bBG9UmQ="
  [mod."github.com/magiconair/properties"]
    version = "v1.8.7"
    hash = "sha256-XQ2bnc2s7/IH3WxEO4GishZurMyKwEclZy1DXg+2xXc="
  [mod."github.com/mitchellh/go-homedir"]
    version = "v1.1.0"
    hash = "sha256-oduBKXHAQG8X6aqLEpqZHs5DOKe84u6WkBwi4W6cv3k="
  [mod."github.com/mitchellh/go-ps"]
    version = "v1.0.0"
    hash = "sha256-HzxVHNLHZpnsBuPcub0G+9jjDcDOsxM/6wifbsxf7EY="
  [mod."github.com/mitchellh/mapstructure"]
    version = "v1.5.0"
    hash = "sha256-ztVhGQXs67MF8UadVvG72G3ly0ypQW0IRDdOOkjYwoE="
  [mod."github.com/moutend/go-wca"]
    version = "v0.1.2-0.20190422112502-0fa027b3d89a"
    hash = "sha256-dNA4t+HsNGvor7TRvEeAiIa3MuP9HrmAji3dKt4hjCA="
  [mod."github.com/nu7hatch/gouuid"]
    version = "v0.0.0-20131221200532-179d4d0c4d8d"
    hash = "sha256-kjtBbQTeMAMtNAA/W35XuOtr7VCwBDW8EZUHXnp0Xsc="
  [mod."github.com/oxtoacart/bpool"]
    version = "v0.0.0-20190530202638-03653db5a59c"
    hash = "sha256-Jaw3QTrj05MwADtv7lSjwMACp8s2Z/ratmxPw0t9LbM="
  [mod."github.com/pelletier/go-toml"]
    version = "v1.9.5"
    hash = "sha256-RJ9K1BTId0Mled7S66iGgxHkZ5JKEIsrrNaEfM8aImc="
  [mod."github.com/pelletier/go-toml/v2"]
    version = "v2.2.0"
    hash = "sha256-hbjvVGN0puPwpMq2bDlixeuUj8+we3BOgwZuY7/SM+Y="
  [mod."github.com/sagikazarmark/locafero"]
    version = "v0.4.0"
    hash = "sha256-7I1Oatc7GAaHgAqBFO6Tv4IbzFiYeU9bJAfJhXuWaXk="
  [mod."github.com/sagikazarmark/slog-shim"]
    version = "v0.1.0"
    hash = "sha256-F92BQXXmn3mCwu3mBaGh+joTRItQDSDhsjU6SofkYdA="
  [mod."github.com/sourcegraph/conc"]
    version = "v0.3.0"
    hash = "sha256-mIdMs9MLAOBKf3/0quf1iI3v8uNWydy7ae5MFa+F2Ko="
  [mod."github.com/spf13/afero"]
    version = "v1.11.0"
    hash = "sha256-+rV3cDZr13N8E0rJ7iHmwsKYKH+EhV+IXBut+JbBiIE="
  [mod."github.com/spf13/cast"]
    version = "v1.6.0"
    hash = "sha256-hxioqRZfXE0AE5099wmn3YG0AZF8Wda2EB4c7zHF6zI="
  [mod."github.com/spf13/jwalterweatherman"]
    version = "v1.1.0"
    hash = "sha256-62BQtqTLF/eVrTOr7pUXE7AiHRjOVC8jQs3/Ehmflfs="
  [mod."github.com/spf13/pflag"]
    version = "v1.0.5"
    hash = "sha256-w9LLYzxxP74WHT4ouBspH/iQZXjuAh2WQCHsuvyEjAw="
  [mod."github.com/spf13/viper"]
    version = "v1.18.2"
    hash = "sha256-MXYbK6w1LEaoZ2/L/STF3WU1tbK+7NwGVxUCLKPkwks="
  [mod."github.com/subosito/gotenv"]
    version = "v1.6.0"
    hash = "sha256-LspbjTniiq2xAICSXmgqP7carwlNaLqnCTQfw2pa80A="
  [mod."github.com/tadvi/systray"]
    version = "v0.0.0-20190226123456-11a2b8fa57af"
    hash = "sha256-o0Z+nrd8l5A/CjJAW7lq5cpjdbaihfqiu5laLnSjJS8="
  [mod."github.com/thoas/go-funk"]
    version = "v0.9.3"
    hash = "sha256-XliI/+pUfN2IjRl2deL/FUO2k377r56aPwYeWy/ABMs="
  [mod."go.opentelemetry.io/otel"]
    version = "v1.24.0"
    hash = "sha256-VGyV7EqJX6mRY0Ecyg+g0IZy+dt1GES4r9txQcaTNUg="
  [mod."go.opentelemetry.io/otel/metric"]
    version = "v1.24.0"
    hash = "sha256-KB5UQiaVmbB2VZO3al4WHb5HY79ioWaAQjaGkUKLvP8="
  [mod."go.opentelemetry.io/otel/trace"]
    version = "v1.24.0"
    hash = "sha256-FHP0hg+i7+wxCsM0u/5hQcgvvr3D+lq8o/7E/HkaW4s="
  [mod."go.uber.org/atomic"]
    version = "v1.11.0"
    hash = "sha256-TyYws/cSPVqYNffFX0gbDml1bD4bBGcysrUWU7mHPIY="
  [mod."go.uber.org/multierr"]
    version = "v1.11.0"
    hash = "sha256-Lb6rHHfR62Ozg2j2JZy3MKOMKdsfzd1IYTR57r3Mhp0="
  [mod."go.uber.org/zap"]
    version = "v1.27.0"
    hash = "sha256-8655KDrulc4Das3VRduO9MjCn8ZYD5WkULjCvruaYsU="
  [mod."golang.org/x/exp"]
    version = "v0.0.0-20240318143956-a85f2c67cd81"
    hash = "sha256-HjEmpjgXqIuGc5rsTVkg6OPAN2fGhfkska7cwRu1qaw="
  [mod."golang.org/x/sys"]
    version = "v0.18.0"
    hash = "sha256-bIFhfFp7Sj0E1gcE3X3l/jecCfSRLgrkb8f0Yr6tVR0="
  [mod."golang.org/x/text"]
    version = "v0.14.0"
    hash = "sha256-yh3B0tom1RfzQBf1RNmfdNWF1PtiqxV41jW1GVS6JAg="
  [mod."gopkg.in/Knetic/govaluate.v3"]
    version = "v3.0.0"
    hash = "sha256-KbbDS9otEvQ72j6t8NNGLJJw7i0DXeNr7zohtm9KgIY="
  [mod."gopkg.in/ini.v1"]
    version = "v1.67.0"
    hash = "sha256-V10ahGNGT+NLRdKUyRg1dos5RxLBXBk1xutcnquc/+4="
  [mod."gopkg.in/yaml.v2"]
    version = "v2.4.0"
    hash = "sha256-uVEGglIedjOIGZzHW4YwN1VoRSTK8o0eGZqzd+TNdd0="
  [mod."gopkg.in/yaml.v3"]
    version = "v3.0.1"
    hash = "sha256-FqL9TKYJ0XkNwJFnq9j0VvJ5ZUU1RvH/52h/f5bkYAU="
