schema = 3

[mod]
  [mod."fyne.io/systray"]
    version = "v1.11.0"
    hash = "sha256-ablbI3h0ASRS+EJGDxPBS2dPj2nutPkF7jtqkzu9Khs="
  [mod."git.sr.ht/~jackmordaunt/go-toast"]
    version = "v1.1.2"
    hash = "sha256-xNlul602ezXiEiRP67VEECk2a4kW1n9aHWqa+8UKT4k="
  [mod."github.com/GRbit/go-pcre"]
    version = "v1.0.1"
    hash = "sha256-oyuGwiWlmrFqD/05kp415LgA2jeBTCg4YWWkcPvauFk="
  [mod."github.com/esiqveland/notify"]
    version = "v0.13.3"
    hash = "sha256-y+WqZAtCEZacAaqxdEEE+8gh2xhiPMpwM7IUmpE6og0="
  [mod."github.com/fsnotify/fsnotify"]
    version = "v1.9.0"
    hash = "sha256-WtpE1N6dpHwEvIub7Xp/CrWm0fd6PX7MKA4PV44rp2g="
  [mod."github.com/gen2brain/beeep"]
    version = "v0.11.1"
    hash = "sha256-VUAJYg+WKm2NUyoV5LngKBCBhNV7esPK37rKl5o3lyo="
  [mod."github.com/go-ole/go-ole"]
    version = "v1.3.0"
    hash = "sha256-tF8t3VcV71jQ4jbPL91BwR59AKDpUAFV1waIKzkXJu8="
  [mod."github.com/go-toast/toast"]
    version = "v0.0.0-20190211030409-01e6764cf0a4"
    hash = "sha256-A2CcALnNGu+5xk3qWaIyKBUzGuJXcw1iIUOQZnCzInA="
  [mod."github.com/go-viper/mapstructure/v2"]
    version = "v2.4.0"
    hash = "sha256-lLfcV9z4n94hDhgyXJlde4bFB0hfzlbh+polqcJCwGE="
  [mod."github.com/godbus/dbus/v5"]
    version = "v5.1.0"
    hash = "sha256-xOCMJpQK3KTmHTPn/CdqI4j0eENCtMmJDgAIoYqYOEY="
  [mod."github.com/jackmordaunt/icns/v3"]
    version = "v3.0.1"
    hash = "sha256-BBS5+lIOPn3HVBr4S15YYgvffQxy24BAOAQml4CJ2s4="
  [mod."github.com/jacobsa/go-serial"]
    version = "v0.0.0-20180131005756-15cf729a72d4"
    hash = "sha256-jU7RnOBsexiPqG4BXjolYHYbURW2Ky09IXtYATbyB5c="
  [mod."github.com/jfreymuth/pulse"]
    version = "v0.1.1"
    hash = "sha256-fcPllz50gRzebPGK0NqK3MuXLZesvA6nb1qYe7TdfPo="
  [mod."github.com/lxn/win"]
    version = "v0.0.0-20210218163916-a377121e959e"
    hash = "sha256-aEbdhcd+xYIATwUdYeuN4gZ/wymgSM5JlFZ7bBG9UmQ="
  [mod."github.com/mitchellh/go-ps"]
    version = "v1.0.0"
    hash = "sha256-HzxVHNLHZpnsBuPcub0G+9jjDcDOsxM/6wifbsxf7EY="
  [mod."github.com/moutend/go-wca"]
    version = "v0.1.2-0.20190422112502-0fa027b3d89a"
    hash = "sha256-dNA4t+HsNGvor7TRvEeAiIa3MuP9HrmAji3dKt4hjCA="
  [mod."github.com/nfnt/resize"]
    version = "v0.0.0-20180221191011-83c6a9932646"
    hash = "sha256-yvPV+HlDOyJsiwAcVHQkmtw8DHSXyw+cXHkigXm8rAA="
  [mod."github.com/nu7hatch/gouuid"]
    version = "v0.0.0-20131221200532-179d4d0c4d8d"
    hash = "sha256-kjtBbQTeMAMtNAA/W35XuOtr7VCwBDW8EZUHXnp0Xsc="
  [mod."github.com/pelletier/go-toml/v2"]
    version = "v2.2.4"
    hash = "sha256-8qQIPldbsS5RO8v/FW/se3ZsAyvLzexiivzJCbGRg2Q="
  [mod."github.com/sagikazarmark/locafero"]
    version = "v0.12.0"
    hash = "sha256-EXk9S5Z5sYyApAzCgHIugsGMbt/pHWRfHYFZH5D+5Ws="
  [mod."github.com/sergeymakinen/go-bmp"]
    version = "v1.0.0"
    hash = "sha256-8ADMMD2M+h264VGwMxBcIBfpou/2zysdo+xtWXHf9C0="
  [mod."github.com/sergeymakinen/go-ico"]
    version = "v1.0.0"
    hash = "sha256-ljOz3cREtFSoqdVtfPo2tgk25QA90Bfn/iHJYKF9roQ="
  [mod."github.com/sourcegraph/conc"]
    version = "v0.3.1-0.20240121214520-5f936abd7ae8"
    hash = "sha256-AUNFlY6K7s1aoW/vb4pjK84ROdnVZY1i6cOmdeG+wN8="
  [mod."github.com/spf13/afero"]
    version = "v1.15.0"
    hash = "sha256-LhcezbOqfuBzacytbqck0hNUxi6NbWNhifUc5/9uHQ8="
  [mod."github.com/spf13/cast"]
    version = "v1.10.0"
    hash = "sha256-dQ6Qqf26IZsa6XsGKP7GDuCj+WmSsBmkBwGTDfue/rk="
  [mod."github.com/spf13/pflag"]
    version = "v1.0.10"
    hash = "sha256-uDPnWjHpSrzXr17KEYEA1yAbizfcsfo5AyztY2tS6ZU="
  [mod."github.com/spf13/viper"]
    version = "v1.21.0"
    hash = "sha256-A9A8i7HH/ge4j3hw7G++HNj8BjhhpZKvxHhfY+QAxkI="
  [mod."github.com/subosito/gotenv"]
    version = "v1.6.0"
    hash = "sha256-LspbjTniiq2xAICSXmgqP7carwlNaLqnCTQfw2pa80A="
  [mod."github.com/tadvi/systray"]
    version = "v0.0.0-20190226123456-11a2b8fa57af"
    hash = "sha256-o0Z+nrd8l5A/CjJAW7lq5cpjdbaihfqiu5laLnSjJS8="
  [mod."github.com/thoas/go-funk"]
    version = "v0.9.3"
    hash = "sha256-XliI/+pUfN2IjRl2deL/FUO2k377r56aPwYeWy/ABMs="
  [mod."go.uber.org/multierr"]
    version = "v1.11.0"
    hash = "sha256-Lb6rHHfR62Ozg2j2JZy3MKOMKdsfzd1IYTR57r3Mhp0="
  [mod."go.uber.org/zap"]
    version = "v1.27.0"
    hash = "sha256-8655KDrulc4Das3VRduO9MjCn8ZYD5WkULjCvruaYsU="
  [mod."go.yaml.in/yaml/v3"]
    version = "v3.0.4"
    hash = "sha256-NkGFiDPoCxbr3LFsI6OCygjjkY0rdmg5ggvVVwpyDQ4="
  [mod."golang.org/x/sys"]
    version = "v0.37.0"
    hash = "sha256-5aT0xP02sW1o9sfJHtWoGGNVYDdwb9FyiX/n6RAlzPo="
  [mod."golang.org/x/text"]
    version = "v0.30.0"
    hash = "sha256-VPT1Y2zzgdk+Q3Gx8hdwKdxbVh0/Zn/HwDpILCW3ZNA="
  [mod."gopkg.in/yaml.v3"]
    version = "v3.0.1"
    hash = "sha256-FqL9TKYJ0XkNwJFnq9j0VvJ5ZUU1RvH/52h/f5bkYAU="
