schema = 3

[mod]
  [mod."fyne.io/systray"]
    version = "v1.11.0"
    hash = "sha256-ablbI3h0ASRS+EJGDxPBS2dPj2nutPkF7jtqkzu9Khs="
  [mod."github.com/GRbit/go-pcre"]
    version = "v1.0.1"
    hash = "sha256-oyuGwiWlmrFqD/05kp415LgA2jeBTCg4YWWkcPvauFk="
  [mod."github.com/fsnotify/fsnotify"]
    version = "v1.9.0"
    hash = "sha256-WtpE1N6dpHwEvIub7Xp/CrWm0fd6PX7MKA4PV44rp2g="
  [mod."github.com/gen2brain/beeep"]
    version = "v0.0.0-20240516210008-9c006672e7f4"
    hash = "sha256-gg7g1HeWDgIMA2p/K5DDQNnHoPJsnv3bzTGtIwRi7cc="
  [mod."github.com/go-ole/go-ole"]
    version = "v1.3.0"
    hash = "sha256-tF8t3VcV71jQ4jbPL91BwR59AKDpUAFV1waIKzkXJu8="
  [mod."github.com/go-toast/toast"]
    version = "v0.0.0-20190211030409-01e6764cf0a4"
    hash = "sha256-A2CcALnNGu+5xk3qWaIyKBUzGuJXcw1iIUOQZnCzInA="
  [mod."github.com/go-viper/mapstructure/v2"]
    version = "v2.2.1"
    hash = "sha256-3BcbxiZQp3eglk+vaYnRIDGT4dQ9K8aLrTPODbToI/Q="
  [mod."github.com/godbus/dbus/v5"]
    version = "v5.1.0"
    hash = "sha256-xOCMJpQK3KTmHTPn/CdqI4j0eENCtMmJDgAIoYqYOEY="
  [mod."github.com/jacobsa/go-serial"]
    version = "v0.0.0-20180131005756-15cf729a72d4"
    hash = "sha256-jU7RnOBsexiPqG4BXjolYHYbURW2Ky09IXtYATbyB5c="
  [mod."github.com/jfreymuth/pulse"]
    version = "v0.1.1"
    hash = "sha256-fcPllz50gRzebPGK0NqK3MuXLZesvA6nb1qYe7TdfPo="
  [mod."github.com/lxn/win"]
    version = "v0.0.0-20210218163916-a377121e959e"
    hash = "sha256-aEbdhcd+xYIATwUdYeuN4gZ/wymgSM5JlFZ7bBG9UmQ="
  [mod."github.com/mitchellh/go-ps"]
    version = "v1.0.0"
    hash = "sha256-HzxVHNLHZpnsBuPcub0G+9jjDcDOsxM/6wifbsxf7EY="
  [mod."github.com/moutend/go-wca"]
    version = "v0.1.2-0.20190422112502-0fa027b3d89a"
    hash = "sha256-dNA4t+HsNGvor7TRvEeAiIa3MuP9HrmAji3dKt4hjCA="
  [mod."github.com/nu7hatch/gouuid"]
    version = "v0.0.0-20131221200532-179d4d0c4d8d"
    hash = "sha256-kjtBbQTeMAMtNAA/W35XuOtr7VCwBDW8EZUHXnp0Xsc="
  [mod."github.com/pelletier/go-toml/v2"]
    version = "v2.2.3"
    hash = "sha256-fE++SVgnCGdnFZoROHWuYjIR7ENl7k9KKxQrRTquv/o="
  [mod."github.com/sagikazarmark/locafero"]
    version = "v0.9.0"
    hash = "sha256-x17b2oqwELO7OQofzITRWfJHomFud3jLezUl8AGnvXc="
  [mod."github.com/sourcegraph/conc"]
    version = "v0.3.0"
    hash = "sha256-mIdMs9MLAOBKf3/0quf1iI3v8uNWydy7ae5MFa+F2Ko="
  [mod."github.com/spf13/afero"]
    version = "v1.14.0"
    hash = "sha256-d/ARtboq2myaDFI3p1rfCrrS0wtlp2TCbjyhBNWjSEc="
  [mod."github.com/spf13/cast"]
    version = "v1.7.1"
    hash = "sha256-BjX0aY/PC37gIdMc7JhMgvhWFsksGdAcp2FgzpuvkPo="
  [mod."github.com/spf13/pflag"]
    version = "v1.0.6"
    hash = "sha256-NjrK0FZPIfO/p2xtL1J7fOBQNTZAPZOC6Cb4aMMvhxI="
  [mod."github.com/spf13/viper"]
    version = "v1.20.1"
    hash = "sha256-gbCM0k7RAlvn7jpSuWB2LX5Nip9vgwsPNGbDXTI7JvM="
  [mod."github.com/subosito/gotenv"]
    version = "v1.6.0"
    hash = "sha256-LspbjTniiq2xAICSXmgqP7carwlNaLqnCTQfw2pa80A="
  [mod."github.com/tadvi/systray"]
    version = "v0.0.0-20190226123456-11a2b8fa57af"
    hash = "sha256-o0Z+nrd8l5A/CjJAW7lq5cpjdbaihfqiu5laLnSjJS8="
  [mod."github.com/thoas/go-funk"]
    version = "v0.9.3"
    hash = "sha256-XliI/+pUfN2IjRl2deL/FUO2k377r56aPwYeWy/ABMs="
  [mod."go.uber.org/multierr"]
    version = "v1.11.0"
    hash = "sha256-Lb6rHHfR62Ozg2j2JZy3MKOMKdsfzd1IYTR57r3Mhp0="
  [mod."go.uber.org/zap"]
    version = "v1.27.0"
    hash = "sha256-8655KDrulc4Das3VRduO9MjCn8ZYD5WkULjCvruaYsU="
  [mod."golang.org/x/sys"]
    version = "v0.31.0"
    hash = "sha256-aulv5obCrhheMlSq7seUgP3C29nfZABwiQ4IBNisgME="
  [mod."golang.org/x/text"]
    version = "v0.23.0"
    hash = "sha256-TiYX1K4DYpP1dEV06whOm43xyOntjrPFi+VAdncoeCY="
  [mod."gopkg.in/yaml.v3"]
    version = "v3.0.1"
    hash = "sha256-FqL9TKYJ0XkNwJFnq9j0VvJ5ZUU1RvH/52h/f5bkYAU="
